name: RobotTests
on:
  push:
    branches:
      - master
      - next
  pull_request:


jobs:
  test:
    name: Run Robot Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Robot cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install robot
        run: pip install -r requirements.txt

      - name: Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Start the service
        run: |
          cp .env.example .env
          docker compose -f docker-compose.build.yml up -d auth postgres traefik --wait

      - name: Perform healthchecks
        run: |
          docker compose ps -a
          docker compose logs
          # wget --retry-connrefused --retry-on-http-error=502 http://localhost:8901/api/health || (docker compose logs && exit 1)

      - name: Run robot tests
        run: |
          robot -d out $(find -type d -name robot)

      - name: Show logs
        if: failure()
        run: docker compose logs

      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: out

